language: node_js
node_js:
  - 14.15.1

services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t codediger/udagram-cd-p3-frontend .
  - docker tag udagram-cd-p3-frontend codediger/udagram-cd-p3-frontend:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push codediger/udagram-cd-p3-frontend